[package]
name = "gcip"
version = "0.1.0"
authors = ["Brian Cook <bcook@rowdydog.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
regex = "1"
