[package]
name = "gcip"
version = "0.1.0"
authors = ["Brian Cook <bcook@rowdydog.com>"]
edition = "2018"

[dependencies]
clap = "3.2.1"
structopt = { version = "0.3", default-features = false }
regex = "1.5.6"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
