version: 2.1

#orbs:
#  win: circleci/windows@2.4.0

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
#    executor: win/default
    steps:
      - run:
          name: "dump Git configuration"
          command: |
            ls
