version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: "multiline test 1"
          command: |
            dir
            git config --list
      - run:
          name: "allow https when fetching from GitHub"
          command: |
            git config --global --unset url."ssh://git@github.com".insteadof
          shell: cmd.exe
      - run:
          name: "multiline test 2"
          command: |
            dir
            git config --list
