version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  version: 2
  all_jobs:
    jobs:
      - j1

jobs:
  j1:
#    executor: win/default
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202008-01
    steps:
      - checkout

      - run:
          name: "dump Git configuration"
          command: |
            git config --list
      - run:
          name: "allow https when fetching from GitHub"
          command: |
            git config --global --unset url.ssh://git@github.com.insteadof
      - run:
          name: "dump Git configuration"
          command: |
            git config --list

#      - run:
#          name: "Install Rust the chocolatey way"
#          command: |
#            choco install rust-ms
#      - run:
#          name: compile release
#          command: |
#            cargo build --release

#      - run:
#          name: "download rustup-init"
#          command: |
#            curl --proto https --tlsv1.2 -sSf https://win.rustup.rs/x86_64 --output rustup-init.exe
#          shell: bash.exe
#      - run:
#          name: "install Rust"
#          command: |
#            rustup-init -y -v --default-host x86_64-pc-windows-msvc --default-toolchain stable --profile minimal
#          shell: cmd.exe
#      - run:
#          name: "compile release version"
#          command: |
#            %USERPROFILE%\.cargo\bin\cargo build --release
#          shell: cmd.exe

      - run:
          name: "download rustup-init"
          command: |
            curl --proto https --tlsv1.2 -sSf https://sh.rustup.rs --output rustup.rs --verbose
            ls -la
      - run:
          name: "install Rust"
          command: |
            ls -la
            sh rustup -y -v --default-host x86_64-unknown-linux-gnu --default-toolchain stable --profile minimal
      - run:
          name: "compile release version"
          command: |
            cargo build --release

