# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1

#yaml_anchors:
#  machine-executor: &machine_executor
#    machine:
#      docker_layer_caching: false
#      image: ubuntu-2004:202008-01

# Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
#  welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run

#orbs:
#  win: circleci/windows@2.4.0 # The Windows orb give you everything you need to start using the Windows executor.
#jobs:
#  build: # name of your job
#    executor: win/default # executor type
#    steps:
#      # Commands are run in a Windows virtual machine environment
#      - checkout
#      - run: Write-Host 'Hello, Windows'
#      - run:
#          name: compile release
#          command: |
#            cargo build --release

#jobs:
#  build:
#    machine:
#      image: ubuntu-2004:202101-01
#    steps:
#      - checkout
#      - run:
#          name: compile release
#          command: |
#            cargo build --release
#      - run:
#          name: "7-Zip test"
#          command: |
#            7z

#      - run:
#          name: dump environment
#          command: |
#            set
#          shell: cmd.exe

# Works to download but the destination directory is unknown.
#            $client = new-object System.Net.WebClient
#            $client.DownloadFile('https://win.rustup.rs', "rustup-init.exe")

orbs:
  win: circleci/windows@2.4.0
jobs:
  build:
    executor: win/default
    steps:
#      - checkout
#      - run:
#          name: "Install Rust the chocolatey way"
#          command: |
#            choco install rust-ms
#      - run:
#          name: "allow https when fetching from GitHub"
#          command: |
#            git config --global --unset "url.ssh://git@github.com.insteadof"
#      - run:
#          name: compile release
#          command: |
#            cargo build --release

      - checkout
      - run:
          name: "download rustup-init"
          command: |
            curl --proto https --tlsv1.2 -sSf https://win.rustup.rs/x86_64 --output rustup-init.exe
          shell: bash.exe
      - run:
          name: "install Rust"
          command: |
            rustup-init -y -v --default-host x86_64-pc-windows-msvc --default-toolchain stable --profile minimal
          shell: cmd.exe
      - run:
          name: "allow https when fetching from GitHub"
          command: |
            git config --global --unset "url.ssh://git@github.com.insteadof" || true
          shell: cmd.exe
      - run:
          name: "compile release version"
          command: |
            cargo build --release
          shell: cmd.exe
